Complete modal-dialog code for task-02
Marcinw-455/RemoteRepo pull request #7
Opened 2021-03-07 14:49 UTC by Marcinw-455

2021-03-08 15:35 UTC, MateuszKuriata requested changes

2021-03-08 15:35 UTC, MateuszKuriata commented on README.md
> +document.getElementById
this is not necessary there;

2021-03-08 15:35 UTC, MateuszKuriata commented on dist/index.html
> +
fix indents and white new lines

2021-03-08 15:35 UTC, MateuszKuriata commented on src/js/dialog.js
> +    document.querySelector(".modal-dialog").appendChild(modalContent);
you can refer to this element by variable instead of querying this element from DOM

2021-03-08 15:35 UTC, MateuszKuriata commented on src/js/dialog.js
> +    document.querySelector(".modal-content").appendChild(modalHeader);
same here, and all querySelectors below

2021-03-08 15:35 UTC, MateuszKuriata commented on src/js/dialog.js
> +
please remove empty lines

2021-03-08 15:35 UTC, MateuszKuriata commented on src/js/dialog.js
> +            alert("Sukces");
typo

2021-03-08 15:35 UTC, MateuszKuriata commented on src/index.js
> +import createDialogElement from "./js/dialog.js";
please fix imports and code execution

2021-03-08 16:31 UTC, Marcinw-455 commented
the code has been corrected

2021-03-10 00:07 UTC, Marcinw-455 commented
code and structure is improved

2021-03-11 20:55 UTC, MateuszKuriata approved these changes

2021-03-11 21:20 UTC, merged