Create wall build app for js experience
Marcinw-455/RemoteRepo pull request #8
Opened 2021-03-13 21:17 UTC by Marcinw-455

2021-03-14 20:56 UTC, MateuszKuriata requested changes

2021-03-14 20:56 UTC, MateuszKuriata commented on src/js/loop.js
> +    for (let step = 0; step < loops; step++) {
body of two loops are almost the same, it might be better to use one loop, and execute if inside. or move loop to another method and add parameter with element class

2021-03-16 00:56 UTC, Marcinw-455 commented
new commands have been added to the package.json file and the code and structure of the application have been improved.

2021-03-17 11:56 UTC, MateuszKuriata approved these changes

2021-03-17 11:57 UTC, merged